export const useCountryDDIList = [
    { name: "Afeganistão", code: "AF", ddi: "+93", mask: ["(##) #######"] },
    { name: "Albânia", code: "AL", ddi: "+355", mask: ["(##) #######"] },
    { name: "Argélia", code: "DZ", ddi: "+213", mask: ["(##) ##-##-##"] },
    { name: "Argentina", code: "AR", ddi: "+54", mask: ["(##) ####-####"] },
    { name: "Armênia", code: "AM", ddi: "+374", mask: ["(##) ###-##-##"] },
    { name: "Austrália", code: "AU", ddi: "+61", mask: ["(##) #### ###", "(##) #######"] },
    { name: "Áustria", code: "AT", ddi: "+43", mask: ["(###) ###-###"] },
    { name: "Azerbaijão", code: "AZ", ddi: "+994", mask: ["(##) ###-##-##"] },
    { name: "Bahamas", code: "BS", ddi: "+1-242", mask: ["(###) ###-####"] },
    { name: "Bahrein", code: "BH", ddi: "+973", mask: ["(###) ###-###"] },
    { name: "Bangladesh", code: "BD", ddi: "+880", mask: ["(##) ####-####"] },
    { name: "Barbados", code: "BB", ddi: "+1-246", mask: ["(###) ###-####"] },
    { name: "Bielorrússia", code: "BY", ddi: "+375", mask: ["(##) ###-##-##"] },
    { name: "Bélgica", code: "BE", ddi: "+32", mask: ["(##) ###-##-##"] },
    { name: "Brasil", code: "BR", ddi: "+55", mask: ["(##) ####-####", "(##) #####-####"] },
    { name: "Canadá", code: "CA", ddi: "+1", mask: ["(###) ###-####"] },
    { name: "Chile", code: "CL", ddi: "+56", mask: ["(##) ####-####"] },
    { name: "China", code: "CN", ddi: "+86", mask: ["(###) ####-####"] },
    { name: "Colômbia", code: "CO", ddi: "+57", mask: ["(##) ####-####"] },
    { name: "Costa Rica", code: "CR", ddi: "+506", mask: ["(##) ####-####"] },
    { name: "Croácia", code: "HR", ddi: "+385", mask: ["(##) ###-####"] },
    { name: "Chipre", code: "CY", ddi: "+357", mask: ["(##) #######"] },
    { name: "República Tcheca", code: "CZ", ddi: "+420", mask: ["(###) ###-###"] },
    { name: "Dinamarca", code: "DK", ddi: "+45", mask: ["(##) ## ## ##"] },
    { name: "República Dominicana", code: "DO", ddi: "+1-809", mask: ["(###) ###-####"] },
    { name: "Equador", code: "EC", ddi: "+593", mask: ["(##) ###-####"] },
    { name: "Egito", code: "EG", ddi: "+20", mask: ["(##) ####-####"] },
    { name: "El Salvador", code: "SV", ddi: "+503", mask: ["(##) ####-####"] },
    { name: "Estônia", code: "EE", ddi: "+372", mask: ["(###) ###-###"] },
    { name: "Finlândia", code: "FI", ddi: "+358", mask: ["(##) #######"] },
    { name: "França", code: "FR", ddi: "+33", mask: ["(##) ## ## ## ##"] },
    { name: "Geórgia", code: "GE", ddi: "+995", mask: ["(##) ###-##-##"] },
    { name: "Alemanha", code: "DE", ddi: "+49", mask: ["(###) ###-####"] },
    { name: "Gana", code: "GH", ddi: "+233", mask: ["(##) ####-####"] },
    { name: "Grécia", code: "GR", ddi: "+30", mask: ["(##) ####-####"] },
    { name: "Guatemala", code: "GT", ddi: "+502", mask: ["(##) ####-####"] },
    { name: "Honduras", code: "HN", ddi: "+504", mask: ["(##) ####-####"] },
    { name: "Hungria", code: "HU", ddi: "+36", mask: ["(##) ###-###"] },
    { name: "Islândia", code: "IS", ddi: "+354", mask: ["(###) ###-###"] },
    { name: "Índia", code: "IN", ddi: "+91", mask: ["(##) #####-#####"] },
    { name: "Indonésia", code: "ID", ddi: "+62", mask: ["(##) ####-####"] },
    { name: "Irlanda", code: "IE", ddi: "+353", mask: ["(##) ###-####"] },
    { name: "Israel", code: "IL", ddi: "+972", mask: ["(##) ###-####"] },
    { name: "Itália", code: "IT", ddi: "+39", mask: ["(##) ####-####"] },
    { name: "Jamaica", code: "JM", ddi: "+1-876", mask: ["(###) ###-####"] },
    { name: "Japão", code: "JP", ddi: "+81", mask: ["(##) ####-####"] },
    { name: "Jordânia", code: "JO", ddi: "+962", mask: ["(##) ####-####"] },
    { name: "Cazaquistão", code: "KZ", ddi: "+7", mask: ["(###) ###-##-##"] },
    { name: "Quênia", code: "KE", ddi: "+254", mask: ["(##) ###-####"] },
    { name: "Kuwait", code: "KW", ddi: "+965", mask: ["(###) ###-####"] },
    { name: "Letônia", code: "LV", ddi: "+371", mask: ["(###) ###-###"] },
    { name: "Líbano", code: "LB", ddi: "+961", mask: ["(##) ###-###"] },
    { name: "Lituânia", code: "LT", ddi: "+370", mask: ["(###) ###-####"] },
    { name: "Luxemburgo", code: "LU", ddi: "+352", mask: ["(###) ###-###"] },
    { name: "Malásia", code: "MY", ddi: "+60", mask: ["(##) ####-####"] },
    { name: "Malta", code: "MT", ddi: "+356", mask: ["(###) ###-###"] },
    { name: "México", code: "MX", ddi: "+52", mask: ["(##) ####-####"] },
    { name: "Marrocos", code: "MA", ddi: "+212", mask: ["(##) ###-###"] },
    { name: "Países Baixos", code: "NL", ddi: "+31", mask: ["(##) ###-####"] },
    { name: "Nova Zelândia", code: "NZ", ddi: "+64", mask: ["(##) #######"] },
    { name: "Nicarágua", code: "NI", ddi: "+505", mask: ["(##) ####-####"] },
    { name: "Nigéria", code: "NG", ddi: "+234", mask: ["(##) #######"] },
    { name: "Noruega", code: "NO", ddi: "+47", mask: ["(##) ## ## ##"] },
    { name: "Paquistão", code: "PK", ddi: "+92", mask: ["(##) ####-####"] },
    { name: "Panamá", code: "PA", ddi: "+507", mask: ["(##) ####-####"] },
    { name: "Peru", code: "PE", ddi: "+51", mask: ["(##) ####-####"] },
    { name: "Filipinas", code: "PH", ddi: "+63", mask: ["(##) ####-####"] },
    { name: "Polônia", code: "PL", ddi: "+48", mask: ["(##) ###-##-##"] },
    { name: "Portugal", code: "PT", ddi: "+351", mask: ["(##) ###-###"] },
    { name: "Qatar", code: "QA", ddi: "+974", mask: ["(###) ###-###"] },
    { name: "Romênia", code: "RO", ddi: "+40", mask: ["(###) ###-###"] },
    { name: "Rússia", code: "RU", ddi: "+7", mask: ["(###) ###-##-##"] },
    { name: "Arábia Saudita", code: "SA", ddi: "+966", mask: ["(###) ###-####"] },
    { name: "Singapura", code: "SG", ddi: "+65", mask: ["(##) #### ####"] },
    { name: "Eslováquia", code: "SK", ddi: "+421", mask: ["(###) ###-###"] },
    { name: "Eslovênia", code: "SI", ddi: "+386", mask: ["(###) ###-###"] },
    { name: "África do Sul", code: "ZA", ddi: "+27", mask: ["(##) #######"] },
    { name: "Coreia do Sul", code: "KR", ddi: "+82", mask: ["(##) ####-####"] },
    { name: "Espanha", code: "ES", ddi: "+34", mask: ["(##) ###-##-##"] },
    { name: "Suécia", code: "SE", ddi: "+46", mask: ["(##) ###-###"] },
    { name: "Suíça", code: "CH", ddi: "+41", mask: ["(###) ###-####"] },
    { name: "Taiwan", code: "TW", ddi: "+886", mask: ["(##) ####-####"] },
    { name: "Tailândia", code: "TH", ddi: "+66", mask: ["(##) ####-####"] },
    { name: "Turquia", code: "TR", ddi: "+90", mask: ["(###) ###-##-##"] },
    { name: "Ucrânia", code: "UA", ddi: "+380", mask: ["(###) ###-##-##"] },
    { name: "Emirados Árabes Unidos", code: "AE", ddi: "+971", mask: ["(###) ###-####"] },
    { name: "Reino Unido", code: "GB", ddi: "+44", mask: ["(####) ### ####"] },
    { name: "Estados Unidos", code: "US", ddi: "+1", mask: ["(###) ###-####"] },
    { name: "Uruguai", code: "UY", ddi: "+598", mask: ["(##) ####-####"] },
    { name: "Venezuela", code: "VE", ddi: "+58", mask: ["(##) ####-####"] },
    { name: "Vietnã", code: "VN", ddi: "+84", mask: ["(##) ####-####"] },
    { name: "Paraguai", code: "PY", ddi: "+595", mask: ["(##) ####-####"] }
].map(country => ({
    ...country,
    mask: country?.mask.map(mask => `${country.ddi} ${mask}`)
}));

export function useCountryDDIFind (property: "code" | "ddi", search: string) {
    return useCountryDDIList.find(l => l?.[property]?.toLowerCase() === String(search)?.toLowerCase());
}